// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/


// TAO_IDL - Generated from
// be/be_codegen.cpp:652

#ifndef _TAO_IDL_DATAWRITERREMOTES_D1V3B0_CPP_
#define _TAO_IDL_DATAWRITERREMOTES_D1V3B0_CPP_


#include "DataWriterRemoteS.h"
#include "tao/PortableServer/Operation_Table_Perfect_Hash.h"
#include "tao/PortableServer/Upcall_Command.h"
#include "tao/PortableServer/Upcall_Wrapper.h"
#include "tao/TAO_Server_Request.h"
#include "tao/ORB_Core.h"
#include "tao/Profile.h"
#include "tao/Stub.h"
#include "tao/IFR_Client_Adapter.h"
#include "tao/Object_T.h"
#include "tao/AnyTypeCode/TypeCode.h"
#include "tao/AnyTypeCode/DynamicC.h"
#include "tao/CDR.h"
#include "tao/operation_details.h"
#include "tao/PortableInterceptor.h"
#include "ace/Dynamic_Service.h"
#include "ace/Malloc_Allocator.h"

// TAO_IDL - Generated from
// be/be_interface.cpp:1868

class TAO_OpenDDS_DCPS_DataWriterRemote_Perfect_Hash_OpTable
  : public TAO_Perfect_Hash_OpTable
{
private:
  unsigned int hash (const char *str, unsigned int len);

public:
  const TAO_operation_db_entry * lookup (const char *str, unsigned int len);
};

/* C++ code produced by gperf version 2.8 (ACE version) */
/* Command-line: /home/borotech/Development/ACE_wrappers/bin/ace_gperf -m -M -J -c -C -D -E -T -f 0 -F 0,0 -a -o -t -p -K opname -L C++ -Z TAO_OpenDDS_DCPS_DataWriterRemote_Perfect_Hash_OpTable -N lookup  */
unsigned int
TAO_OpenDDS_DCPS_DataWriterRemote_Perfect_Hash_OpTable::hash (const char *str, unsigned int len)
{
  static const unsigned char asso_values[] =
    {
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
     27, 27, 27, 27, 27,  0, 27,  0, 27, 27,
      0,  5, 27, 27, 27, 27, 27, 27, 27, 27,
      5, 27, 27, 27,  0,  0,  0,  0, 27, 27,
     27, 27, 27, 27, 27, 27, 27, 27,
    };
  return len + asso_values[(int) str[len - 1]] + asso_values[(int) str[0]];
}

const TAO_operation_db_entry *
TAO_OpenDDS_DCPS_DataWriterRemote_Perfect_Hash_OpTable::lookup (const char *str, unsigned int len)
{
  enum
    {
      TOTAL_KEYWORDS = 10,
      MIN_WORD_LENGTH = 5,
      MAX_WORD_LENGTH = 26,
      MIN_HASH_VALUE = 5,
      MAX_HASH_VALUE = 26,
      HASH_VALUE_RANGE = 22,
      DUPLICATES = 0,
      WORDLIST_SIZE = 15
    };

  static const TAO_operation_db_entry wordlist[] =
    {
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_is_a", &TAO_ServantBase::_is_a_thru_poa_skel, 0},
      {"",0,0},{"",0,0},{"",0,0},{"",0,0},
      {"_component", &TAO_ServantBase::_component_thru_poa_skel, 0},
      {"",0,0},{"",0,0},
      {"_non_existent", &TAO_ServantBase::_non_existent_thru_poa_skel, 0},
      {"_repository_id", &TAO_ServantBase::_repository_id_thru_poa_skel, 0},
      {"_interface", &TAO_ServantBase::_interface_skel, 0},
      {"",0,0},{"",0,0},{"",0,0},
      {"remove_associations", &POA_OpenDDS::DCPS::DataWriterRemote::remove_associations_skel, 0},
      {"add_association", &POA_OpenDDS::DCPS::DataWriterRemote::add_association_skel, 0},
      {"",0,0},{"",0,0},
      {"update_incompatible_qos", &POA_OpenDDS::DCPS::DataWriterRemote::update_incompatible_qos_skel, 0},
      {"",0,0},
      {"association_complete", &POA_OpenDDS::DCPS::DataWriterRemote::association_complete_skel, 0},
      {"update_subscription_params", &POA_OpenDDS::DCPS::DataWriterRemote::update_subscription_params_skel, 0},
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE && key >= MIN_HASH_VALUE)
        {
          const char *s = wordlist[key].opname;

          if (*str == *s && !ACE_OS::strncmp (str + 1, s + 1, len - 1))
            return &wordlist[key];
        }
    }
  return 0;
}

static TAO_OpenDDS_DCPS_DataWriterRemote_Perfect_Hash_OpTable tao_OpenDDS_DCPS_DataWriterRemote_optable;

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:93

POA_OpenDDS::DCPS::DataWriterRemote::DataWriterRemote (void)
  : TAO_ServantBase ()
{
  this->optable_ = &tao_OpenDDS_DCPS_DataWriterRemote_optable;
}

POA_OpenDDS::DCPS::DataWriterRemote::DataWriterRemote (const DataWriterRemote& rhs)
  : TAO_Abstract_ServantBase (rhs),
    TAO_ServantBase (rhs)
{
}

POA_OpenDDS::DCPS::DataWriterRemote::~DataWriterRemote (void)
{
}

namespace POA_OpenDDS
{
  
  namespace DCPS
  {
    

    // TAO_IDL - Generated from
    // be/be_visitor_operation/upcall_command_ss.cpp:83

    class add_association_DataWriterRemote
      : public TAO::Upcall_Command
    {
    public:
      inline add_association_DataWriterRemote (
        POA_OpenDDS::DCPS::DataWriterRemote * servant,
        TAO_Operation_Details const * operation_details,
        TAO::Argument * const args[])
        : servant_ (servant)
          , operation_details_ (operation_details)
          , args_ (args)
      {
      }

      virtual void execute (void)
      {
        TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_type arg_1 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::GUID_t> (
            this->operation_details_,
            this->args_,
            1);
          
        TAO::SArg_Traits< ::OpenDDS::DCPS::ReaderAssociation>::in_arg_type arg_2 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::ReaderAssociation> (
            this->operation_details_,
            this->args_,
            2);
          
        TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_type arg_3 =
          TAO::Portable_Server::get_in_arg< ::ACE_InputCDR::to_boolean> (
            this->operation_details_,
            this->args_,
            3);
          
        this->servant_->add_association (
          arg_1
          , arg_2
          , arg_3);
      }
    
    private:
      POA_OpenDDS::DCPS::DataWriterRemote * const servant_;
      TAO_Operation_Details const * const operation_details_;
      TAO::Argument * const * const args_;
    };
  }
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_OpenDDS::DCPS::DataWriterRemote::add_association_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_yourId;
  TAO::SArg_Traits< ::OpenDDS::DCPS::ReaderAssociation>::in_arg_val _tao_reader;
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_val _tao_active;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_yourId,
      &_tao_reader,
      &_tao_active
    };
  
  static size_t const nargs = 4;

  POA_OpenDDS::DCPS::DataWriterRemote * const impl =
    dynamic_cast<POA_OpenDDS::DCPS::DataWriterRemote *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  add_association_DataWriterRemote command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_OpenDDS
{
  
  namespace DCPS
  {
    

    // TAO_IDL - Generated from
    // be/be_visitor_operation/upcall_command_ss.cpp:83

    class association_complete_DataWriterRemote
      : public TAO::Upcall_Command
    {
    public:
      inline association_complete_DataWriterRemote (
        POA_OpenDDS::DCPS::DataWriterRemote * servant,
        TAO_Operation_Details const * operation_details,
        TAO::Argument * const args[])
        : servant_ (servant)
          , operation_details_ (operation_details)
          , args_ (args)
      {
      }

      virtual void execute (void)
      {
        TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_type arg_1 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::GUID_t> (
            this->operation_details_,
            this->args_,
            1);
          
        this->servant_->association_complete (
          arg_1);
      }
    
    private:
      POA_OpenDDS::DCPS::DataWriterRemote * const servant_;
      TAO_Operation_Details const * const operation_details_;
      TAO::Argument * const * const args_;
    };
  }
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_OpenDDS::DCPS::DataWriterRemote::association_complete_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_remote_id;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_remote_id
    };
  
  static size_t const nargs = 2;

  POA_OpenDDS::DCPS::DataWriterRemote * const impl =
    dynamic_cast<POA_OpenDDS::DCPS::DataWriterRemote *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  association_complete_DataWriterRemote command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_OpenDDS
{
  
  namespace DCPS
  {
    

    // TAO_IDL - Generated from
    // be/be_visitor_operation/upcall_command_ss.cpp:83

    class remove_associations_DataWriterRemote
      : public TAO::Upcall_Command
    {
    public:
      inline remove_associations_DataWriterRemote (
        POA_OpenDDS::DCPS::DataWriterRemote * servant,
        TAO_Operation_Details const * operation_details,
        TAO::Argument * const args[])
        : servant_ (servant)
          , operation_details_ (operation_details)
          , args_ (args)
      {
      }

      virtual void execute (void)
      {
        TAO::SArg_Traits< ::OpenDDS::DCPS::ReaderIdSeq>::in_arg_type arg_1 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::ReaderIdSeq> (
            this->operation_details_,
            this->args_,
            1);
          
        TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_type arg_2 =
          TAO::Portable_Server::get_in_arg< ::ACE_InputCDR::to_boolean> (
            this->operation_details_,
            this->args_,
            2);
          
        this->servant_->remove_associations (
          arg_1
          , arg_2);
      }
    
    private:
      POA_OpenDDS::DCPS::DataWriterRemote * const servant_;
      TAO_Operation_Details const * const operation_details_;
      TAO::Argument * const * const args_;
    };
  }
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_OpenDDS::DCPS::DataWriterRemote::remove_associations_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::OpenDDS::DCPS::ReaderIdSeq>::in_arg_val _tao_readers;
  TAO::SArg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_val _tao_notify_lost;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_readers,
      &_tao_notify_lost
    };
  
  static size_t const nargs = 3;

  POA_OpenDDS::DCPS::DataWriterRemote * const impl =
    dynamic_cast<POA_OpenDDS::DCPS::DataWriterRemote *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  remove_associations_DataWriterRemote command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_OpenDDS
{
  
  namespace DCPS
  {
    

    // TAO_IDL - Generated from
    // be/be_visitor_operation/upcall_command_ss.cpp:83

    class update_incompatible_qos_DataWriterRemote
      : public TAO::Upcall_Command
    {
    public:
      inline update_incompatible_qos_DataWriterRemote (
        POA_OpenDDS::DCPS::DataWriterRemote * servant,
        TAO_Operation_Details const * operation_details,
        TAO::Argument * const args[])
        : servant_ (servant)
          , operation_details_ (operation_details)
          , args_ (args)
      {
      }

      virtual void execute (void)
      {
        TAO::SArg_Traits< ::OpenDDS::DCPS::IncompatibleQosStatus>::in_arg_type arg_1 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::IncompatibleQosStatus> (
            this->operation_details_,
            this->args_,
            1);
          
        this->servant_->update_incompatible_qos (
          arg_1);
      }
    
    private:
      POA_OpenDDS::DCPS::DataWriterRemote * const servant_;
      TAO_Operation_Details const * const operation_details_;
      TAO::Argument * const * const args_;
    };
  }
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_OpenDDS::DCPS::DataWriterRemote::update_incompatible_qos_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::OpenDDS::DCPS::IncompatibleQosStatus>::in_arg_val _tao_status;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_status
    };
  
  static size_t const nargs = 2;

  POA_OpenDDS::DCPS::DataWriterRemote * const impl =
    dynamic_cast<POA_OpenDDS::DCPS::DataWriterRemote *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  update_incompatible_qos_DataWriterRemote command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}


namespace POA_OpenDDS
{
  
  namespace DCPS
  {
    

    // TAO_IDL - Generated from
    // be/be_visitor_operation/upcall_command_ss.cpp:83

    class update_subscription_params_DataWriterRemote
      : public TAO::Upcall_Command
    {
    public:
      inline update_subscription_params_DataWriterRemote (
        POA_OpenDDS::DCPS::DataWriterRemote * servant,
        TAO_Operation_Details const * operation_details,
        TAO::Argument * const args[])
        : servant_ (servant)
          , operation_details_ (operation_details)
          , args_ (args)
      {
      }

      virtual void execute (void)
      {
        TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_type arg_1 =
          TAO::Portable_Server::get_in_arg< ::OpenDDS::DCPS::GUID_t> (
            this->operation_details_,
            this->args_,
            1);
          
        TAO::SArg_Traits< ::DDS::StringSeq>::in_arg_type arg_2 =
          TAO::Portable_Server::get_in_arg< ::DDS::StringSeq> (
            this->operation_details_,
            this->args_,
            2);
          
        this->servant_->update_subscription_params (
          arg_1
          , arg_2);
      }
    
    private:
      POA_OpenDDS::DCPS::DataWriterRemote * const servant_;
      TAO_Operation_Details const * const operation_details_;
      TAO::Argument * const * const args_;
    };
  }
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_ss.cpp:171

void POA_OpenDDS::DCPS::DataWriterRemote::update_subscription_params_skel (
  TAO_ServerRequest & server_request,
  TAO::Portable_Server::Servant_Upcall *TAO_INTERCEPTOR (servant_upcall),
  TAO_ServantBase *servant)
{
#if TAO_HAS_INTERCEPTORS == 1
  static ::CORBA::TypeCode_ptr const * const exceptions = 0;
  static ::CORBA::ULong const nexceptions = 0;
#endif /* TAO_HAS_INTERCEPTORS */

  TAO::SArg_Traits< void>::ret_val retval;
  TAO::SArg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_readerId;
  TAO::SArg_Traits< ::DDS::StringSeq>::in_arg_val _tao_exprParams;

  TAO::Argument * const args[] =
    {
      &retval,
      &_tao_readerId,
      &_tao_exprParams
    };
  
  static size_t const nargs = 3;

  POA_OpenDDS::DCPS::DataWriterRemote * const impl =
    dynamic_cast<POA_OpenDDS::DCPS::DataWriterRemote *> (servant);

  if (!impl)
    {
      throw ::CORBA::INTERNAL ();
    }

  update_subscription_params_DataWriterRemote command (
    impl,
    server_request.operation_details (),
    args);
  
  TAO::Upcall_Wrapper upcall_wrapper;
  upcall_wrapper.upcall (server_request
                         , args
                         , nargs
                         , command
#if TAO_HAS_INTERCEPTORS == 1
                         , servant_upcall
                         , exceptions
                         , nexceptions
#endif  /* TAO_HAS_INTERCEPTORS == 1 */
                         );
}



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:166



::CORBA::Boolean POA_OpenDDS::DCPS::DataWriterRemote::_is_a (const char* value)
{
  return
    (
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataWriterRemote:1.0"
        ) == 0 ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    );
}

const char* POA_OpenDDS::DCPS::DataWriterRemote::_interface_repository_id (void) const
{
  return "IDL:OpenDDS/DCPS/DataWriterRemote:1.0";
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:426

void POA_OpenDDS::DCPS::DataWriterRemote::_dispatch (
  TAO_ServerRequest & req,
  TAO::Portable_Server::Servant_Upcall* servant_upcall)
{
  this->synchronous_upcall_dispatch (req, servant_upcall, this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_ss.cpp:373

OpenDDS::DCPS::DataWriterRemote *
POA_OpenDDS::DCPS::DataWriterRemote::_this (void)
{
  TAO_Stub *stub = this->_create_stub ();

  TAO_Stub_Auto_Ptr safe_stub (stub);
  ::CORBA::Object_ptr tmp = CORBA::Object_ptr ();

  ::CORBA::Boolean const _tao_opt_colloc =
    stub->servant_orb_var ()->orb_core ()->optimize_collocation_objects ();
  
  ACE_NEW_RETURN (
      tmp,
      ::CORBA::Object (stub, _tao_opt_colloc, this),
      0);
  
  ::CORBA::Object_var obj = tmp;
  (void) safe_stub.release ();

  typedef ::OpenDDS::DCPS::DataWriterRemote STUB_SCOPED_NAME;
  return
    TAO::Narrow_Utils<STUB_SCOPED_NAME>::unchecked_narrow (
        obj.in ());
}

#endif /* ifndef */

