// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "DataWriterRemoteC.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DataWriterRemoteC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for OpenDDS::DCPS::DataWriterRemote.

OpenDDS::DCPS::DataWriterRemote_ptr
TAO::Objref_Traits<OpenDDS::DCPS::DataWriterRemote>::duplicate (
    OpenDDS::DCPS::DataWriterRemote_ptr p)
{
  return OpenDDS::DCPS::DataWriterRemote::_duplicate (p);
}

void
TAO::Objref_Traits<OpenDDS::DCPS::DataWriterRemote>::release (
    OpenDDS::DCPS::DataWriterRemote_ptr p)
{
  ::CORBA::release (p);
}

OpenDDS::DCPS::DataWriterRemote_ptr
TAO::Objref_Traits<OpenDDS::DCPS::DataWriterRemote>::nil (void)
{
  return OpenDDS::DCPS::DataWriterRemote::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<OpenDDS::DCPS::DataWriterRemote>::marshal (
    const OpenDDS::DCPS::DataWriterRemote_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
OpenDDS::DCPS::DataWriterRemote::add_association (
  const ::OpenDDS::DCPS::RepoId & yourId,
  const ::OpenDDS::DCPS::ReaderAssociation & reader,
  ::CORBA::Boolean active)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_yourId (yourId);
  TAO::Arg_Traits< ::OpenDDS::DCPS::ReaderAssociation>::in_arg_val _tao_reader (reader);
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_val _tao_active (active);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_yourId,
      &_tao_reader,
      &_tao_active
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      4,
      "add_association",
      15,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
OpenDDS::DCPS::DataWriterRemote::association_complete (
  const ::OpenDDS::DCPS::RepoId & remote_id)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_remote_id (remote_id);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_remote_id
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "association_complete",
      20,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
OpenDDS::DCPS::DataWriterRemote::remove_associations (
  const ::OpenDDS::DCPS::ReaderIdSeq & readers,
  ::CORBA::Boolean notify_lost)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OpenDDS::DCPS::ReaderIdSeq>::in_arg_val _tao_readers (readers);
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::in_arg_val _tao_notify_lost (notify_lost);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_readers,
      &_tao_notify_lost
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "remove_associations",
      19,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
OpenDDS::DCPS::DataWriterRemote::update_incompatible_qos (
  const ::OpenDDS::DCPS::IncompatibleQosStatus & status)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OpenDDS::DCPS::IncompatibleQosStatus>::in_arg_val _tao_status (status);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_status
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "update_incompatible_qos",
      23,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY,
      TAO::TAO_ONEWAY_INVOCATION
      
    );

  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:91

void
OpenDDS::DCPS::DataWriterRemote::update_subscription_params (
  const ::OpenDDS::DCPS::RepoId & readerId,
  const ::DDS::StringSeq & exprParams)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::OpenDDS::DCPS::GUID_t>::in_arg_val _tao_readerId (readerId);
  TAO::Arg_Traits< ::DDS::StringSeq>::in_arg_val _tao_exprParams (exprParams);

  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_readerId,
      &_tao_exprParams
    };

  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "update_subscription_params",
      26,
      TAO::TAO_CO_NONE | TAO::TAO_CO_THRU_POA_STRATEGY
      
    );

  _tao_call.invoke (0, 0);
}

OpenDDS::DCPS::DataWriterRemote::DataWriterRemote (void)
{
}

OpenDDS::DCPS::DataWriterRemote::~DataWriterRemote (void)
{
}

OpenDDS::DCPS::DataWriterRemote_ptr
OpenDDS::DCPS::DataWriterRemote::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<DataWriterRemote>::narrow (
        _tao_objref,
        "IDL:OpenDDS/DCPS/DataWriterRemote:1.0");
}

OpenDDS::DCPS::DataWriterRemote_ptr
OpenDDS::DCPS::DataWriterRemote::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return
    TAO::Narrow_Utils<DataWriterRemote>::unchecked_narrow (
        _tao_objref);
}

OpenDDS::DCPS::DataWriterRemote_ptr
OpenDDS::DCPS::DataWriterRemote::_nil (void)
{
  return 0;
}

OpenDDS::DCPS::DataWriterRemote_ptr
OpenDDS::DCPS::DataWriterRemote::_duplicate (DataWriterRemote_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
OpenDDS::DCPS::DataWriterRemote::_tao_release (DataWriterRemote_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
OpenDDS::DCPS::DataWriterRemote::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataWriterRemote:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* OpenDDS::DCPS::DataWriterRemote::_interface_repository_id (void) const
{
  return "IDL:OpenDDS/DCPS/DataWriterRemote:1.0";
}

::CORBA::Boolean
OpenDDS::DCPS::DataWriterRemote::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:54

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::DCPS::DataWriterRemote_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::DCPS::DataWriterRemote_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;

  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::OpenDDS::DCPS::DataWriterRemote RHS_SCOPED_NAME;

  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (obj.in ());
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



