/* -*- C++ -*- */
/* Generated by ../bin/opendds_idl version 3.6 (ACE version 6.2a_p7) running on input file CorbaSeq/CharSeq.idl*/
#ifndef OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_AJXUDX
#define OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_AJXUDX
#include "dds/DCPS/Definitions.h"
#include "tao/CharSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: CharSeq */

namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_find_size(const CORBA::CharSeq& seq, size_t& size, size_t& padding);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const CORBA::CharSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm, CORBA::CharSeq& seq);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_skip_over(Serializer& ser, CORBA::CharSeq*);

}  }

#endif

/* End TYPEDEF: CharSeq */

/* End MODULE: CORBA */
#endif /* OPENDDS_IDL_GENERATED_CHARSEQTYPESUPPORTIMPL_H_AJXUDX */
