/* -*- C++ -*- */
/* Generated by ../bin/opendds_idl version 3.6 (ACE version 6.2a_p7) running on input file CorbaSeq/FloatSeq.idl*/
#ifndef OPENDDS_IDL_GENERATED_FLOATSEQTYPESUPPORTIMPL_H_2EUIMX
#define OPENDDS_IDL_GENERATED_FLOATSEQTYPESUPPORTIMPL_H_2EUIMX
#include "dds/DCPS/Definitions.h"
#include "tao/FloatSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: FloatSeq */

namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_find_size(const CORBA::FloatSeq& seq, size_t& size, size_t& padding);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const CORBA::FloatSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm, CORBA::FloatSeq& seq);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_skip_over(Serializer& ser, CORBA::FloatSeq*);

}  }

#endif

/* End TYPEDEF: FloatSeq */

/* End MODULE: CORBA */
#endif /* OPENDDS_IDL_GENERATED_FLOATSEQTYPESUPPORTIMPL_H_2EUIMX */
