/* -*- C++ -*- */
/* Generated by ../bin/opendds_idl version 3.6 (ACE version 6.2a_p7) running on input file CorbaSeq/ShortSeq.idl*/
#ifndef OPENDDS_IDL_GENERATED_SHORTSEQTYPESUPPORTIMPL_H_TWTHIP
#define OPENDDS_IDL_GENERATED_SHORTSEQTYPESUPPORTIMPL_H_TWTHIP
#include "dds/DCPS/Definitions.h"
#include "tao/ShortSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ShortSeq */

namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_find_size(const CORBA::ShortSeq& seq, size_t& size, size_t& padding);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const CORBA::ShortSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm, CORBA::ShortSeq& seq);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_skip_over(Serializer& ser, CORBA::ShortSeq*);

}  }

#endif

/* End TYPEDEF: ShortSeq */

/* End MODULE: CORBA */
#endif /* OPENDDS_IDL_GENERATED_SHORTSEQTYPESUPPORTIMPL_H_TWTHIP */
