/* -*- C++ -*- */
/* Generated by ../bin/opendds_idl version 3.6 (ACE version 6.2a_p7) running on input file CorbaSeq/UShortSeq.idl*/
#ifndef OPENDDS_IDL_GENERATED_USHORTSEQTYPESUPPORTIMPL_H_RS89DM
#define OPENDDS_IDL_GENERATED_USHORTSEQTYPESUPPORTIMPL_H_RS89DM
#include "dds/DCPS/Definitions.h"
#include "tao/UShortSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: UShortSeq */

namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_find_size(const CORBA::UShortSeq& seq, size_t& size, size_t& padding);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const CORBA::UShortSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm, CORBA::UShortSeq& seq);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_skip_over(Serializer& ser, CORBA::UShortSeq*);

}  }

#endif

/* End TYPEDEF: UShortSeq */

/* End MODULE: CORBA */
#endif /* OPENDDS_IDL_GENERATED_USHORTSEQTYPESUPPORTIMPL_H_RS89DM */
