/* -*- C++ -*- */
/* Generated by ../bin/opendds_idl version 3.6 (ACE version 6.2a_p7) running on input file CorbaSeq/WStringSeq.idl*/
#ifndef OPENDDS_IDL_GENERATED_WSTRINGSEQTYPESUPPORTIMPL_H_DWU4QR
#define OPENDDS_IDL_GENERATED_WSTRINGSEQTYPESUPPORTIMPL_H_DWU4QR
#include "dds/DCPS/Definitions.h"
#include "tao/WStringSeqC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/dcps_export.h"


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: WStringSeq */

namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_find_size(const CORBA::WStringSeq& seq, size_t& size, size_t& padding);

OpenDDS_Dcps_Export
bool operator<<(Serializer& strm, const CORBA::WStringSeq& seq);

OpenDDS_Dcps_Export
bool operator>>(Serializer& strm, CORBA::WStringSeq& seq);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

OpenDDS_Dcps_Export
void gen_skip_over(Serializer& ser, CORBA::WStringSeq*);

}  }

#endif

/* End TYPEDEF: WStringSeq */

/* End MODULE: CORBA */
#endif /* OPENDDS_IDL_GENERATED_WSTRINGSEQTYPESUPPORTIMPL_H_DWU4QR */
