// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376

#include "DCPS/DdsDcps_pch.h"
#include "DdsDcpsDomainC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DdsDcpsDomainC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDS::DomainParticipantListener.

DDS::DomainParticipantListener_ptr
TAO::Objref_Traits<DDS::DomainParticipantListener>::duplicate (
    DDS::DomainParticipantListener_ptr p)
{
  return DDS::DomainParticipantListener::_duplicate (p);
}

void
TAO::Objref_Traits<DDS::DomainParticipantListener>::release (
    DDS::DomainParticipantListener_ptr p)
{
  ::CORBA::release (p);
}

DDS::DomainParticipantListener_ptr
TAO::Objref_Traits<DDS::DomainParticipantListener>::nil (void)
{
  return DDS::DomainParticipantListener::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDS::DomainParticipantListener>::marshal (
    const DDS::DomainParticipantListener_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDS::DomainParticipantListener::DomainParticipantListener (void)
{}

DDS::DomainParticipantListener::~DomainParticipantListener (void)
{
}

DDS::DomainParticipantListener_ptr
DDS::DomainParticipantListener::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipantListener::_duplicate (
      dynamic_cast<DomainParticipantListener_ptr> (_tao_objref)
    );
}

DDS::DomainParticipantListener_ptr
DDS::DomainParticipantListener::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipantListener::_duplicate (
      dynamic_cast<DomainParticipantListener_ptr> (_tao_objref)
    );
}

DDS::DomainParticipantListener_ptr
DDS::DomainParticipantListener::_nil (void)
{
  return 0;
}

DDS::DomainParticipantListener_ptr
DDS::DomainParticipantListener::_duplicate (DomainParticipantListener_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDS::DomainParticipantListener::_tao_release (DomainParticipantListener_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDS::DomainParticipantListener::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Listener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TopicListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriterListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/PublisherListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReaderListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/SubscriberListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DomainParticipantListener:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDS::DomainParticipantListener::_interface_repository_id (void) const
{
  return "IDL:DDS/DomainParticipantListener:1.0";
}

::CORBA::Boolean
DDS::DomainParticipantListener::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDS::DomainParticipant.

DDS::DomainParticipant_ptr
TAO::Objref_Traits<DDS::DomainParticipant>::duplicate (
    DDS::DomainParticipant_ptr p)
{
  return DDS::DomainParticipant::_duplicate (p);
}

void
TAO::Objref_Traits<DDS::DomainParticipant>::release (
    DDS::DomainParticipant_ptr p)
{
  ::CORBA::release (p);
}

DDS::DomainParticipant_ptr
TAO::Objref_Traits<DDS::DomainParticipant>::nil (void)
{
  return DDS::DomainParticipant::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDS::DomainParticipant>::marshal (
    const DDS::DomainParticipant_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDS::DomainParticipant::DomainParticipant (void)
{}

DDS::DomainParticipant::~DomainParticipant (void)
{
}

DDS::DomainParticipant_ptr
DDS::DomainParticipant::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipant::_duplicate (
      dynamic_cast<DomainParticipant_ptr> (_tao_objref)
    );
}

DDS::DomainParticipant_ptr
DDS::DomainParticipant::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipant::_duplicate (
      dynamic_cast<DomainParticipant_ptr> (_tao_objref)
    );
}

DDS::DomainParticipant_ptr
DDS::DomainParticipant::_nil (void)
{
  return 0;
}

DDS::DomainParticipant_ptr
DDS::DomainParticipant::_duplicate (DomainParticipant_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDS::DomainParticipant::_tao_release (DomainParticipant_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDS::DomainParticipant::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DomainParticipant:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDS::DomainParticipant::_interface_repository_id (void) const
{
  return "IDL:DDS/DomainParticipant:1.0";
}

::CORBA::Boolean
DDS::DomainParticipant::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for DDS::DomainParticipantFactory.

DDS::DomainParticipantFactory_ptr
TAO::Objref_Traits<DDS::DomainParticipantFactory>::duplicate (
    DDS::DomainParticipantFactory_ptr p)
{
  return DDS::DomainParticipantFactory::_duplicate (p);
}

void
TAO::Objref_Traits<DDS::DomainParticipantFactory>::release (
    DDS::DomainParticipantFactory_ptr p)
{
  ::CORBA::release (p);
}

DDS::DomainParticipantFactory_ptr
TAO::Objref_Traits<DDS::DomainParticipantFactory>::nil (void)
{
  return DDS::DomainParticipantFactory::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DDS::DomainParticipantFactory>::marshal (
    const DDS::DomainParticipantFactory_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

DDS::DomainParticipantFactory::DomainParticipantFactory (void)
{}

DDS::DomainParticipantFactory::~DomainParticipantFactory (void)
{
}

DDS::DomainParticipantFactory_ptr
DDS::DomainParticipantFactory::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipantFactory::_duplicate (
      dynamic_cast<DomainParticipantFactory_ptr> (_tao_objref)
    );
}

DDS::DomainParticipantFactory_ptr
DDS::DomainParticipantFactory::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return DomainParticipantFactory::_duplicate (
      dynamic_cast<DomainParticipantFactory_ptr> (_tao_objref)
    );
}

DDS::DomainParticipantFactory_ptr
DDS::DomainParticipantFactory::_nil (void)
{
  return 0;
}

DDS::DomainParticipantFactory_ptr
DDS::DomainParticipantFactory::_duplicate (DomainParticipantFactory_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DDS::DomainParticipantFactory::_tao_release (DomainParticipantFactory_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DDS::DomainParticipantFactory::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DomainParticipantFactory:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DDS::DomainParticipantFactory::_interface_repository_id (void) const
{
  return "IDL:DDS/DomainParticipantFactory:1.0";
}

::CORBA::Boolean
DDS::DomainParticipantFactory::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

