
// -*- C++ -*-
// $Id: Version.h 2648 2015-08-28 17:12:12Z taoadmin $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.py

#define ACE_MAJOR_VERSION 6
#define ACE_MINOR_VERSION 2
#define ACE_BETA_VERSION 0
#define ACE_VERSION "6.2a_p7"
#define ACE_OCI_PATCHLEVEL 7
#define ACE_OCI_REV a
