// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:461

#ifndef _TAO_IDL_RTPSBASEMESSAGETYPESS_9GMVJP_H_
#define _TAO_IDL_RTPSBASEMESSAGETYPESS_9GMVJP_H_

#include /**/ "ace/pre.h"

#include "RtpsBaseMessageTypesC.h"
#include "../../DdsDcpsGuidS.h"
#include "../../DdsDcpsInfoUtilsS.h"
#include "../../DdsDcpsInfrastructureS.h"
#include "tao/PortableServer/Basic_SArguments.h"
#include "tao/PortableServer/Special_Basic_SArguments.h"
#include "tao/PortableServer/BD_String_SArgument_T.h"
#include "tao/PortableServer/Fixed_Size_SArgument_T.h"
#include "tao/PortableServer/Var_Size_SArgument_T.h"
#include "tao/PortableServer/UB_String_SArguments.h"
#include "tao/PortableServer/Fixed_Array_SArgument_T.h"
#include "tao/PortableServer/Var_Array_SArgument_T.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::Time_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::Time_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::OctetArray2_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::RTPS::OctetArray2_var,
            ::OpenDDS::RTPS::OctetArray2_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::VendorId_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::VendorId_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::SequenceNumber_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::SequenceNumber_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::FragmentNumber_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::FragmentNumber_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::OctetArray16_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::RTPS::OctetArray16_var,
            ::OpenDDS::RTPS::OctetArray16_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::Locator_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::Locator_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::LocatorUDPv4_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::LocatorUDPv4_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::TopicKind_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::TopicKind_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::ReliabilityKind_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::ReliabilityKind_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::Count_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::Count_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::ProtocolVersion_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::ProtocolVersion_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::KeyHash_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::KeyHash_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::OctetArray4_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::RTPS::OctetArray4_var,
            ::OpenDDS::RTPS::OctetArray4_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::StatusInfo_t>
    : public
        Fixed_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::StatusInfo_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_STRING256256__SARG_TRAITS_)
#define _STRING256256__SARG_TRAITS_

  template<>
  class SArg_Traits<String256_256>
    : public
        BD_String_SArg_Traits_T<
            CORBA::String_var,
            256,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::ContentFilterProperty_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::ContentFilterProperty_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::FilterResult_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::FilterResult_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::FilterSignature_t_tag>
    : public
        Fixed_Array_SArg_Traits_T<
            ::OpenDDS::RTPS::FilterSignature_t_var,
            ::OpenDDS::RTPS::FilterSignature_t_forany,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::FilterSignatureSeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::FilterSignatureSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::ContentFilterInfo_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::ContentFilterInfo_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::Property_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::Property_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::PropertySeq>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::PropertySeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::EntityName_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::EntityName_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::ParameterList>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::ParameterList,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::OriginalWriterInfo_t>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::OriginalWriterInfo_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:1058

  template<>
  class SArg_Traits< ::OpenDDS::RTPS::Parameter>
    : public
        Var_Size_SArg_Traits_T<
            ::OpenDDS::RTPS::Parameter,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:38

namespace POA_OpenDDS
{
  

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_sh.cpp:38

  namespace RTPS
  {
    
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_sh.cpp:69

  } // module OpenDDS::RTPS

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:69

} // module OpenDDS

#include /**/ "ace/post.h"

#endif /* ifndef */

