// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p7
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_RTPSMESSAGETYPESC_JMDTIX_H_
#define _TAO_IDL_RTPSMESSAGETYPESC_JMDTIX_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "rtps_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "RtpsBaseMessageTypesC.h"
#include "../../DdsDcpsInfoUtilsC.h"
#include "../../DdsDcpsInfrastructureC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OpenDDS_Rtps_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace OpenDDS
{

  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:38

  namespace RTPS
  {

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_OPENDDS_RTPS_LONGSEQ8_CH_)
#define _OPENDDS_RTPS_LONGSEQ8_CH_

    class LongSeq8;

    typedef
      ::TAO_FixedSeq_Var_T<
          LongSeq8
        >
      LongSeq8_var;

    typedef
      ::TAO_Seq_Out_T<
          LongSeq8
        >
      LongSeq8_out;

    class OpenDDS_Rtps_Export LongSeq8
      : public
          ::TAO::bounded_value_sequence<
              ::CORBA::Long,
              8
            >
    {
    public:
      LongSeq8 (void);
      LongSeq8 (
        ::CORBA::ULong length,
        ::CORBA::Long* buffer,
        ::CORBA::Boolean release = false);
      LongSeq8 (const LongSeq8 &);
      virtual ~LongSeq8 (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef LongSeq8_var _var_type;
      typedef LongSeq8_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct SequenceNumberSet;

    typedef
      ::TAO_Var_Var_T<
          SequenceNumberSet
        >
      SequenceNumberSet_var;

    typedef
      ::TAO_Out_T<
          SequenceNumberSet
        >
      SequenceNumberSet_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export SequenceNumberSet
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef SequenceNumberSet_var _var_type;
      typedef SequenceNumberSet_out _out_type;
      
      OpenDDS::RTPS::SequenceNumber_t bitmapBase;
      ::CORBA::ULong numBits;
      OpenDDS::RTPS::LongSeq8 bitmap;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct FragmentNumberSet;

    typedef
      ::TAO_Var_Var_T<
          FragmentNumberSet
        >
      FragmentNumberSet_var;

    typedef
      ::TAO_Out_T<
          FragmentNumberSet
        >
      FragmentNumberSet_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export FragmentNumberSet
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef FragmentNumberSet_var _var_type;
      typedef FragmentNumberSet_out _out_type;
      
      OpenDDS::RTPS::FragmentNumber_t bitmapBase;
      ::CORBA::ULong numBits;
      OpenDDS::RTPS::LongSeq8 bitmap;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_OPENDDS_RTPS_LOCATORLIST_CH_)
#define _OPENDDS_RTPS_LOCATORLIST_CH_

    class LocatorList;

    typedef
      ::TAO_FixedSeq_Var_T<
          LocatorList
        >
      LocatorList_var;

    typedef
      ::TAO_Seq_Out_T<
          LocatorList
        >
      LocatorList_out;

    class OpenDDS_Rtps_Export LocatorList
      : public
          ::TAO::bounded_value_sequence<
              Locator_t,
              8
            >
    {
    public:
      LocatorList (void);
      LocatorList (
        ::CORBA::ULong length,
        Locator_t* buffer,
        ::CORBA::Boolean release = false);
      LocatorList (const LocatorList &);
      virtual ~LocatorList (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef LocatorList_var _var_type;
      typedef LocatorList_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct Header;

    typedef
      ::TAO_Fixed_Var_T<
          Header
        >
      Header_var;

    typedef
      Header &
      Header_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export Header
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef Header_var _var_type;
      typedef Header_out _out_type;
      
      OpenDDS::RTPS::OctetArray4 prefix;
      OpenDDS::RTPS::ProtocolVersion_t version;
      OpenDDS::RTPS::VendorId_t vendorId;
      OpenDDS::RTPS::GuidPrefix_t guidPrefix;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct SubmessageHeader;

    typedef
      ::TAO_Fixed_Var_T<
          SubmessageHeader
        >
      SubmessageHeader_var;

    typedef
      SubmessageHeader &
      SubmessageHeader_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export SubmessageHeader
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef SubmessageHeader_var _var_type;
      typedef SubmessageHeader_out _out_type;
      
      ::CORBA::Octet submessageId;
      ::CORBA::Octet flags;
      ::CORBA::UShort submessageLength;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct AckNackSubmessage;

    typedef
      ::TAO_Var_Var_T<
          AckNackSubmessage
        >
      AckNackSubmessage_var;

    typedef
      ::TAO_Out_T<
          AckNackSubmessage
        >
      AckNackSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export AckNackSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef AckNackSubmessage_var _var_type;
      typedef AckNackSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumberSet readerSNState;
      OpenDDS::RTPS::Count_t count;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DataSubmessage;

    typedef
      ::TAO_Var_Var_T<
          DataSubmessage
        >
      DataSubmessage_var;

    typedef
      ::TAO_Out_T<
          DataSubmessage
        >
      DataSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export DataSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DataSubmessage_var _var_type;
      typedef DataSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      ::CORBA::UShort extraFlags;
      ::CORBA::UShort octetsToInlineQos;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t writerSN;
      OpenDDS::RTPS::ParameterList inlineQos;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DataFragSubmessage;

    typedef
      ::TAO_Var_Var_T<
          DataFragSubmessage
        >
      DataFragSubmessage_var;

    typedef
      ::TAO_Out_T<
          DataFragSubmessage
        >
      DataFragSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export DataFragSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DataFragSubmessage_var _var_type;
      typedef DataFragSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      ::CORBA::UShort extraFlags;
      ::CORBA::UShort octetsToInlineQos;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t writerSN;
      OpenDDS::RTPS::FragmentNumber_t fragmentStartingNum;
      ::CORBA::UShort fragmentsInSubmessage;
      ::CORBA::UShort fragmentSize;
      ::CORBA::ULong sampleSize;
      OpenDDS::RTPS::ParameterList inlineQos;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct GapSubmessage;

    typedef
      ::TAO_Var_Var_T<
          GapSubmessage
        >
      GapSubmessage_var;

    typedef
      ::TAO_Out_T<
          GapSubmessage
        >
      GapSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export GapSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef GapSubmessage_var _var_type;
      typedef GapSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t gapStart;
      OpenDDS::RTPS::SequenceNumberSet gapList;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct HeartBeatSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          HeartBeatSubmessage
        >
      HeartBeatSubmessage_var;

    typedef
      HeartBeatSubmessage &
      HeartBeatSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export HeartBeatSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef HeartBeatSubmessage_var _var_type;
      typedef HeartBeatSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t firstSN;
      OpenDDS::RTPS::SequenceNumber_t lastSN;
      OpenDDS::RTPS::Count_t count;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct HeartBeatFragSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          HeartBeatFragSubmessage
        >
      HeartBeatFragSubmessage_var;

    typedef
      HeartBeatFragSubmessage &
      HeartBeatFragSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export HeartBeatFragSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef HeartBeatFragSubmessage_var _var_type;
      typedef HeartBeatFragSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t writerSN;
      OpenDDS::RTPS::FragmentNumber_t lastFragmentNum;
      OpenDDS::RTPS::Count_t count;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct InfoDestinationSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          InfoDestinationSubmessage
        >
      InfoDestinationSubmessage_var;

    typedef
      InfoDestinationSubmessage &
      InfoDestinationSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export InfoDestinationSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef InfoDestinationSubmessage_var _var_type;
      typedef InfoDestinationSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::GuidPrefix_t guidPrefix;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct InfoReplySubmessage;

    typedef
      ::TAO_Var_Var_T<
          InfoReplySubmessage
        >
      InfoReplySubmessage_var;

    typedef
      ::TAO_Out_T<
          InfoReplySubmessage
        >
      InfoReplySubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export InfoReplySubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef InfoReplySubmessage_var _var_type;
      typedef InfoReplySubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::LocatorList unicastLocatorList;
      OpenDDS::RTPS::LocatorList multicastLocatorList;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct InfoSourceSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          InfoSourceSubmessage
        >
      InfoSourceSubmessage_var;

    typedef
      InfoSourceSubmessage &
      InfoSourceSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export InfoSourceSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef InfoSourceSubmessage_var _var_type;
      typedef InfoSourceSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      ::CORBA::Long unused;
      OpenDDS::RTPS::ProtocolVersion_t version;
      OpenDDS::RTPS::VendorId_t vendorId;
      OpenDDS::RTPS::GuidPrefix_t guidPrefix;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct InfoTimestampSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          InfoTimestampSubmessage
        >
      InfoTimestampSubmessage_var;

    typedef
      InfoTimestampSubmessage &
      InfoTimestampSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export InfoTimestampSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef InfoTimestampSubmessage_var _var_type;
      typedef InfoTimestampSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::Timestamp_t timestamp;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct PadSubmessage;

    typedef
      ::TAO_Fixed_Var_T<
          PadSubmessage
        >
      PadSubmessage_var;

    typedef
      PadSubmessage &
      PadSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export PadSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef PadSubmessage_var _var_type;
      typedef PadSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct NackFragSubmessage;

    typedef
      ::TAO_Var_Var_T<
          NackFragSubmessage
        >
      NackFragSubmessage_var;

    typedef
      ::TAO_Out_T<
          NackFragSubmessage
        >
      NackFragSubmessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export NackFragSubmessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef NackFragSubmessage_var _var_type;
      typedef NackFragSubmessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::EntityId_t readerId;
      OpenDDS::RTPS::EntityId_t writerId;
      OpenDDS::RTPS::SequenceNumber_t writerSN;
      OpenDDS::RTPS::FragmentNumberSet fragmentNumberState;
      OpenDDS::RTPS::Count_t count;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct InfoReplyIp4Submessage;

    typedef
      ::TAO_Fixed_Var_T<
          InfoReplyIp4Submessage
        >
      InfoReplyIp4Submessage_var;

    typedef
      InfoReplyIp4Submessage &
      InfoReplyIp4Submessage_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export InfoReplyIp4Submessage
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef InfoReplyIp4Submessage_var _var_type;
      typedef InfoReplyIp4Submessage_out _out_type;
      
      OpenDDS::RTPS::SubmessageHeader smHeader;
      OpenDDS::RTPS::LocatorUDPv4_t unicastLocator;
      OpenDDS::RTPS::LocatorUDPv4_t multicastLocator;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_enum/enum_ch.cpp:47

    enum SubmessageKind
    {
      RESERVED_0,
      PAD,
      RESERVED_2,
      RESERVED_3,
      RESERVED_4,
      RESERVED_5,
      ACKNACK,
      HEARTBEAT,
      GAP,
      INFO_TS,
      RESERVED_10,
      RESERVED_11,
      INFO_SRC,
      INFO_REPLY_IP4,
      INFO_DST,
      INFO_REPLY,
      RESERVED_16,
      RESERVED_17,
      NACK_FRAG,
      HEARTBEAT_FRAG,
      RESERVED_20,
      DATA,
      DATA_FRAG
    };

    typedef SubmessageKind &SubmessageKind_out;

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    class Submessage;

    typedef
      ::TAO_Var_Var_T<
          Submessage
        >
      Submessage_var;

    typedef
      ::TAO_Out_T<
          Submessage
        >
      Submessage_out;

    class OpenDDS_Rtps_Export Submessage
    {
    public:
      Submessage (void);
      Submessage (const Submessage &);
      ~Submessage (void);

      Submessage &operator= (const Submessage &);

      // TAO_IDL - Generated from
      // be/be_visitor_union/discriminant_ch.cpp:70

      void _d (OpenDDS::RTPS::SubmessageKind);
      OpenDDS::RTPS::SubmessageKind _d (void) const;

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef Submessage_var _var_type;
      typedef Submessage_out _out_type;

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void pad_sm (const OpenDDS::RTPS::PadSubmessage &);
      const OpenDDS::RTPS::PadSubmessage &pad_sm (void) const;
      OpenDDS::RTPS::PadSubmessage &pad_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void acknack_sm (const OpenDDS::RTPS::AckNackSubmessage &);
      const OpenDDS::RTPS::AckNackSubmessage &acknack_sm (void) const;
      OpenDDS::RTPS::AckNackSubmessage &acknack_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void heartbeat_sm (const OpenDDS::RTPS::HeartBeatSubmessage &);
      const OpenDDS::RTPS::HeartBeatSubmessage &heartbeat_sm (void) const;
      OpenDDS::RTPS::HeartBeatSubmessage &heartbeat_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void gap_sm (const OpenDDS::RTPS::GapSubmessage &);
      const OpenDDS::RTPS::GapSubmessage &gap_sm (void) const;
      OpenDDS::RTPS::GapSubmessage &gap_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void info_ts_sm (const OpenDDS::RTPS::InfoTimestampSubmessage &);
      const OpenDDS::RTPS::InfoTimestampSubmessage &info_ts_sm (void) const;
      OpenDDS::RTPS::InfoTimestampSubmessage &info_ts_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void info_src_sm (const OpenDDS::RTPS::InfoSourceSubmessage &);
      const OpenDDS::RTPS::InfoSourceSubmessage &info_src_sm (void) const;
      OpenDDS::RTPS::InfoSourceSubmessage &info_src_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void info_reply_ipv4_sm (const OpenDDS::RTPS::InfoReplyIp4Submessage &);
      const OpenDDS::RTPS::InfoReplyIp4Submessage &info_reply_ipv4_sm (void) const;
      OpenDDS::RTPS::InfoReplyIp4Submessage &info_reply_ipv4_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void info_dst_sm (const OpenDDS::RTPS::InfoDestinationSubmessage &);
      const OpenDDS::RTPS::InfoDestinationSubmessage &info_dst_sm (void) const;
      OpenDDS::RTPS::InfoDestinationSubmessage &info_dst_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void info_reply_sm (const OpenDDS::RTPS::InfoReplySubmessage &);
      const OpenDDS::RTPS::InfoReplySubmessage &info_reply_sm (void) const;
      OpenDDS::RTPS::InfoReplySubmessage &info_reply_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void nack_frag_sm (const OpenDDS::RTPS::NackFragSubmessage &);
      const OpenDDS::RTPS::NackFragSubmessage &nack_frag_sm (void) const;
      OpenDDS::RTPS::NackFragSubmessage &nack_frag_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void hb_frag_sm (const OpenDDS::RTPS::HeartBeatFragSubmessage &);
      const OpenDDS::RTPS::HeartBeatFragSubmessage &hb_frag_sm (void) const;
      OpenDDS::RTPS::HeartBeatFragSubmessage &hb_frag_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void data_sm (const OpenDDS::RTPS::DataSubmessage &);
      const OpenDDS::RTPS::DataSubmessage &data_sm (void) const;
      OpenDDS::RTPS::DataSubmessage &data_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void data_frag_sm (const OpenDDS::RTPS::DataFragSubmessage &);
      const OpenDDS::RTPS::DataFragSubmessage &data_frag_sm (void) const;
      OpenDDS::RTPS::DataFragSubmessage &data_frag_sm (void);

      // TAO_IDL - Generated from
      // be/be_visitor_union_branch/public_ch.cpp:659

      void unknown_sm (const OpenDDS::RTPS::SubmessageHeader &);
      const OpenDDS::RTPS::SubmessageHeader &unknown_sm (void) const;
      OpenDDS::RTPS::SubmessageHeader &unknown_sm (void);
    private:
      OpenDDS::RTPS::SubmessageKind disc_;

      union
      {
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::PadSubmessage pad_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::AckNackSubmessage *acknack_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::HeartBeatSubmessage heartbeat_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::GapSubmessage *gap_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::InfoTimestampSubmessage info_ts_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::InfoSourceSubmessage info_src_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::InfoReplyIp4Submessage info_reply_ipv4_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::InfoDestinationSubmessage info_dst_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::InfoReplySubmessage *info_reply_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::NackFragSubmessage *nack_frag_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::HeartBeatFragSubmessage hb_frag_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::DataSubmessage *data_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::DataFragSubmessage *data_frag_sm_;
        // TAO_IDL - Generated from
        // be/be_visitor_union_branch/private_ch.cpp:522
        OpenDDS::RTPS::SubmessageHeader unknown_sm_;
      } u_;

      /// TAO extension - frees any allocated storage.
      void _reset (void);
    };

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_OPENDDS_RTPS_SUBMESSAGESEQ_CH_)
#define _OPENDDS_RTPS_SUBMESSAGESEQ_CH_

    class SubmessageSeq;

    typedef
      ::TAO_VarSeq_Var_T<
          SubmessageSeq
        >
      SubmessageSeq_var;

    typedef
      ::TAO_Seq_Out_T<
          SubmessageSeq
        >
      SubmessageSeq_out;

    class OpenDDS_Rtps_Export SubmessageSeq
      : public
          ::TAO::unbounded_value_sequence<
              Submessage
            >
    {
    public:
      SubmessageSeq (void);
      SubmessageSeq ( ::CORBA::ULong max);
      SubmessageSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        Submessage* buffer,
        ::CORBA::Boolean release = false);
      SubmessageSeq (const SubmessageSeq &);
      virtual ~SubmessageSeq (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef SubmessageSeq_var _var_type;
      typedef SubmessageSeq_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct ParticipantMessageData;

    typedef
      ::TAO_Var_Var_T<
          ParticipantMessageData
        >
      ParticipantMessageData_var;

    typedef
      ::TAO_Out_T<
          ParticipantMessageData
        >
      ParticipantMessageData_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export ParticipantMessageData
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef ParticipantMessageData_var _var_type;
      typedef ParticipantMessageData_out _out_type;
      
      OpenDDS::RTPS::GUID_t participantGuid;
      OpenDDS::RTPS::OctetSeq data;
    };

    // TAO_IDL - Generated from
    // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_OPENDDS_RTPS_LOCATORSEQ_CH_)
#define _OPENDDS_RTPS_LOCATORSEQ_CH_

    class LocatorSeq;

    typedef
      ::TAO_FixedSeq_Var_T<
          LocatorSeq
        >
      LocatorSeq_var;

    typedef
      ::TAO_Seq_Out_T<
          LocatorSeq
        >
      LocatorSeq_out;

    class OpenDDS_Rtps_Export LocatorSeq
      : public
          ::TAO::unbounded_value_sequence<
              Locator_t
            >
    {
    public:
      LocatorSeq (void);
      LocatorSeq ( ::CORBA::ULong max);
      LocatorSeq (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        Locator_t* buffer,
        ::CORBA::Boolean release = false);
      LocatorSeq (const LocatorSeq &);
      virtual ~LocatorSeq (void);
      

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef LocatorSeq_var _var_type;
      typedef LocatorSeq_out _out_type;
    };

#endif /* end #if !defined */

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct ParticipantProxy_t;

    typedef
      ::TAO_Var_Var_T<
          ParticipantProxy_t
        >
      ParticipantProxy_t_var;

    typedef
      ::TAO_Out_T<
          ParticipantProxy_t
        >
      ParticipantProxy_t_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export ParticipantProxy_t
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef ParticipantProxy_t_var _var_type;
      typedef ParticipantProxy_t_out _out_type;
      
      OpenDDS::RTPS::ProtocolVersion_t protocolVersion;
      OpenDDS::RTPS::GuidPrefix_t guidPrefix;
      OpenDDS::RTPS::VendorId_t vendorId;
      ::CORBA::Boolean expectsInlineQos;
      OpenDDS::RTPS::BuiltinEndpointSet_t availableBuiltinEndpoints;
      OpenDDS::RTPS::LocatorSeq metatrafficUnicastLocatorList;
      OpenDDS::RTPS::LocatorSeq metatrafficMulticastLocatorList;
      OpenDDS::RTPS::LocatorSeq defaultMulticastLocatorList;
      OpenDDS::RTPS::LocatorSeq defaultUnicastLocatorList;
      OpenDDS::RTPS::Count_t manualLivelinessCount;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct SPDPdiscoveredParticipantData;

    typedef
      ::TAO_Var_Var_T<
          SPDPdiscoveredParticipantData
        >
      SPDPdiscoveredParticipantData_var;

    typedef
      ::TAO_Out_T<
          SPDPdiscoveredParticipantData
        >
      SPDPdiscoveredParticipantData_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export SPDPdiscoveredParticipantData
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef SPDPdiscoveredParticipantData_var _var_type;
      typedef SPDPdiscoveredParticipantData_out _out_type;
      
      DDS::ParticipantBuiltinTopicData ddsParticipantData;
      OpenDDS::RTPS::ParticipantProxy_t participantProxy;
      OpenDDS::RTPS::Duration_t leaseDuration;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct WriterProxy_t;

    typedef
      ::TAO_Var_Var_T<
          WriterProxy_t
        >
      WriterProxy_t_var;

    typedef
      ::TAO_Out_T<
          WriterProxy_t
        >
      WriterProxy_t_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export WriterProxy_t
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef WriterProxy_t_var _var_type;
      typedef WriterProxy_t_out _out_type;
      
      OpenDDS::RTPS::GUID_t remoteWriterGuid;
      OpenDDS::RTPS::LocatorSeq unicastLocatorList;
      OpenDDS::RTPS::LocatorSeq multicastLocatorList;
      OpenDDS::DCPS::TransportLocatorSeq allLocators;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DiscoveredWriterData;

    typedef
      ::TAO_Var_Var_T<
          DiscoveredWriterData
        >
      DiscoveredWriterData_var;

    typedef
      ::TAO_Out_T<
          DiscoveredWriterData
        >
      DiscoveredWriterData_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export DiscoveredWriterData
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DiscoveredWriterData_var _var_type;
      typedef DiscoveredWriterData_out _out_type;
      
      DDS::PublicationBuiltinTopicData ddsPublicationData;
      OpenDDS::RTPS::WriterProxy_t writerProxy;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct ReaderProxy_t;

    typedef
      ::TAO_Var_Var_T<
          ReaderProxy_t
        >
      ReaderProxy_t_var;

    typedef
      ::TAO_Out_T<
          ReaderProxy_t
        >
      ReaderProxy_t_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export ReaderProxy_t
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef ReaderProxy_t_var _var_type;
      typedef ReaderProxy_t_out _out_type;
      
      OpenDDS::RTPS::GUID_t remoteReaderGuid;
      ::CORBA::Boolean expectsInlineQos;
      OpenDDS::RTPS::LocatorSeq unicastLocatorList;
      OpenDDS::RTPS::LocatorSeq multicastLocatorList;
      OpenDDS::DCPS::TransportLocatorSeq allLocators;
      OpenDDS::RTPS::GUIDSeq associatedWriters;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DiscoveredReaderData;

    typedef
      ::TAO_Var_Var_T<
          DiscoveredReaderData
        >
      DiscoveredReaderData_var;

    typedef
      ::TAO_Out_T<
          DiscoveredReaderData
        >
      DiscoveredReaderData_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export DiscoveredReaderData
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DiscoveredReaderData_var _var_type;
      typedef DiscoveredReaderData_out _out_type;
      
      DDS::SubscriptionBuiltinTopicData ddsSubscriptionData;
      OpenDDS::RTPS::ReaderProxy_t readerProxy;
      OpenDDS::RTPS::ContentFilterProperty_t contentFilterProperty;
    };

    // TAO_IDL - Generated from
    // be/be_type.cpp:261

    struct DiscoveredTopicData;

    typedef
      ::TAO_Var_Var_T<
          DiscoveredTopicData
        >
      DiscoveredTopicData_var;

    typedef
      ::TAO_Out_T<
          DiscoveredTopicData
        >
      DiscoveredTopicData_out;

    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:51

    struct OpenDDS_Rtps_Export DiscoveredTopicData
    {

      // TAO_IDL - Generated from
      // be/be_type.cpp:307

      
      typedef DiscoveredTopicData_var _var_type;
      typedef DiscoveredTopicData_out _out_type;
      
      DDS::TopicBuiltinTopicData ddsTopicData;
    };
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:67
  
  } // module OpenDDS::RTPS

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module OpenDDS

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::LongSeq8>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::LongSeq8,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::SequenceNumberSet>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::SequenceNumberSet,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::FragmentNumberSet>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::FragmentNumberSet,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::LocatorList>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::LocatorList,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::Header>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::Header,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::SubmessageHeader>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::SubmessageHeader,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::AckNackSubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::AckNackSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::DataSubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::DataSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::DataFragSubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::DataFragSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::GapSubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::GapSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::HeartBeatSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::HeartBeatSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::HeartBeatFragSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::HeartBeatFragSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::InfoDestinationSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::InfoDestinationSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::InfoReplySubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::InfoReplySubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::InfoSourceSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::InfoSourceSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::InfoTimestampSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::InfoTimestampSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::PadSubmessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::PadSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::NackFragSubmessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::NackFragSubmessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::InfoReplyIp4Submessage>
    : public
        Fixed_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::InfoReplyIp4Submessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:904

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::SubmessageKind>
    : public
        Basic_Arg_Traits_T<
            ::OpenDDS::RTPS::SubmessageKind,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:1058

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::Submessage>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::Submessage,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::SubmessageSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::SubmessageSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::ParticipantMessageData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::ParticipantMessageData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::LocatorSeq>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::LocatorSeq,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::ParticipantProxy_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::ParticipantProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::SPDPdiscoveredParticipantData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::SPDPdiscoveredParticipantData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::WriterProxy_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::WriterProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::DiscoveredWriterData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::DiscoveredWriterData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::ReaderProxy_t>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::ReaderProxy_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::DiscoveredReaderData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::DiscoveredReaderData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::OpenDDS::RTPS::DiscoveredTopicData>
    : public
        Var_Size_Arg_Traits_T<
            ::OpenDDS::RTPS::DiscoveredTopicData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_OpenDDS_RTPS_LongSeq8_H_
#define _TAO_CDR_OP_OpenDDS_RTPS_LongSeq8_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::RTPS::LongSeq8 &_tao_sequence);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::RTPS::LongSeq8 &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_OpenDDS_RTPS_LongSeq8_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::SequenceNumberSet &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::SequenceNumberSet &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::FragmentNumberSet &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::FragmentNumberSet &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_OpenDDS_RTPS_LocatorList_H_
#define _TAO_CDR_OP_OpenDDS_RTPS_LocatorList_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::RTPS::LocatorList &_tao_sequence);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::RTPS::LocatorList &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_OpenDDS_RTPS_LocatorList_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::Header &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::Header &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::SubmessageHeader &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::SubmessageHeader &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::AckNackSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::AckNackSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::DataSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::DataSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::DataFragSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::DataFragSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::GapSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::GapSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::HeartBeatSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::HeartBeatSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::HeartBeatFragSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::HeartBeatFragSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::InfoDestinationSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::InfoDestinationSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::InfoReplySubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::InfoReplySubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::InfoSourceSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::InfoSourceSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::InfoTimestampSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::InfoTimestampSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::PadSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::PadSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::NackFragSubmessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::NackFragSubmessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::InfoReplyIp4Submessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::InfoReplyIp4Submessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, OpenDDS::RTPS::SubmessageKind _tao_enumerator);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, OpenDDS::RTPS::SubmessageKind &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_union/cdr_op_ch.cpp:41


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::Submessage &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::Submessage &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_OpenDDS_RTPS_SubmessageSeq_H_
#define _TAO_CDR_OP_OpenDDS_RTPS_SubmessageSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::RTPS::SubmessageSeq &_tao_sequence);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::RTPS::SubmessageSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_OpenDDS_RTPS_SubmessageSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::ParticipantMessageData &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::ParticipantMessageData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_OpenDDS_RTPS_LocatorSeq_H_
#define _TAO_CDR_OP_OpenDDS_RTPS_LocatorSeq_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const OpenDDS::RTPS::LocatorSeq &_tao_sequence);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    OpenDDS::RTPS::LocatorSeq &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_OpenDDS_RTPS_LocatorSeq_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::ParticipantProxy_t &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::ParticipantProxy_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::SPDPdiscoveredParticipantData &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::SPDPdiscoveredParticipantData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::WriterProxy_t &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::WriterProxy_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::DiscoveredWriterData &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::DiscoveredWriterData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::ReaderProxy_t &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::ReaderProxy_t &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::DiscoveredReaderData &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::DiscoveredReaderData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const OpenDDS::RTPS::DiscoveredTopicData &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, OpenDDS::RTPS::DiscoveredTopicData &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "RtpsMessageTypesC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

